language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- "./ci/bin/build.sh"
- "./ci/bin/test.sh"
- "./ci/bin/cover.sh"
- "./ci/bin/report.sh"
